#!/usr/bin/env node

import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, '..');

// Read package.json
const packageJson = JSON.parse(
  readFileSync(join(rootDir, 'package.json'), 'utf-8')
);

// Generate version.ts content
const content = `/**
 * Auto-generated file containing project metadata.
 * Do not edit manually - this file is generated by scripts/generate-version.js
 */

/**
 * Project name from package.json
 */
export const PROJECT_NAME = '${packageJson.name}';

/**
 * Project version from package.json
 */
export const PROJECT_VERSION = '${packageJson.version}';
`;

// Write to src/version.ts
const outputPath = join(rootDir, 'src', 'version.ts');
writeFileSync(outputPath, content, 'utf-8');

console.log(`✓ Generated ${outputPath}`);
console.log(`  PROJECT_NAME: ${packageJson.name}`);
console.log(`  PROJECT_VERSION: ${packageJson.version}`);
