/**
 * Auto-generated file containing project metadata.
 * Do not edit manually - this file is generated by scripts/generate-version.js
 */

/**
 * Project name from package.json
 */
export const PROJECT_NAME = 'v2c-any';

/**
 * Project version from package.json
 */
export const PROJECT_VERSION = '0.7.1';
